### ISSUE TITLE
v5 (SLEEP) Release TODO

### ISSUE THREAD

**Issue by mafintosh** [mafintosh/hypercore#68]
Blockers

* [x] merge sleep branch
* [x] finish api declared by readme
* [x] re-add old tests
* [x] range requests
* [x] refactor selection api
* [x] don't download data if we are writable
* [x] re-impl timeouts when replication
* [x] release v6 of replicaion protocol
* [x] switch to blake2b for discoveryKey / hashing

Non blockers

* [ ] emit critical errors (feed signed, but sig is wrong fx)
* [x] optimize replication (encoding+allocation seems to be a bottleneck)
* [ ] progress monitoring of latest
* [ ] dedup tree nodes when replicating
* [ ] browser support (finish sodium-javascript)

**Comment by mafintosh** [comment]
V5 IS OUT!!!!
